# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  schedule:
    - cron: '* 05 * * *'
    - cron: '* 10 * * *'
    - cron: '* 15 * * *'
    - cron: '* 20 * * *'
    - cron: '* 01 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:        
      - uses: actions/checkout@v3
        with:
          path: main

      - run: git clone https://gitgud.io/khanon/oai-reverse-proxy proxy

      - run: cp main/exec_app.sh proxy/exec_app.sh

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - run: ls .
        working-directory: ./proxy

      - name: Quit MySQL
        run: sudo service mysql stop

      - run: curl https://api.ipify.org > main/addr.txt

      - run: cat main/addr.txt

      # Runs a single command using the runners shell
      - name: The Thing
        working-directory: ./proxy
        run: |
          echo "PORT=3306" >> $GITHUB_ENV
          chmod +x exec_app.sh 
          bash exec_app.sh
